resources:
  - name: gosvc_gitRepo
    type: GitRepo
    configuration:
      path: RjSH1/go-service
      gitProvider: zen1

  - name: gosvc_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: demoArt
      buildName: svc_build
      buildNumber: 1

  - name: gosvc_promoted_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: demoArt
      buildName: svc_build
      buildNumber: 1

  - name: release_bundle
    type: ReleaseBundle
    configuration:
      sourceDistribution: myDist
      name: demo_rb
      version: v1.0.0

  - name: signed_bundle
    type: ReleaseBundle
    configuration:
      sourceDistribution: myDist
      name: demo_rb
      version: v1.0.0

  - name: distribution_rules
    type: DistributionRule
    configuration:
      sourceDistribution: myDist
      serviceName: "*"
      siteName: "*"
      cityName: "*"
      countryCodes:
        - "CN"
        - "GB"

pipelines:
  - name: demo_gosvc
    steps:
      - name: bld_svc
        type: DockerBuild
        configuration:
          dockerFileLocation: .
          dockerFileName: Dockerfile
#           dockerImageName: avinci-docker-local.jfrog.io/gosvc
#          dockerImageName: 146.148.104.158:8082/docker-local/gosvc
          dockerImageName: distpipe.jfrogdev.org/docker-local/gosvc
          dockerImageTag: ${run_number}
          inputResources:
            - name: gosvc_gitRepo
          integrations:
            - name: demoArt

      - name: push_svc
        type: DockerPush
        configuration:
          targetRepository: docker-local
          forceXrayScan: true
          failOnScan: true
          autoPublishBuildInfo: true
          integrations:
            - name: demoArt
          inputSteps:
            - name: bld_svc
          outputResources:
            - name: gosvc_build_info

      - name: promote_svc_build
        type: PromoteBuild
        configuration:
          targetRepository: docker
          integrations:
            - name: demoArt
          inputResources:
            - name: gosvc_build_info
          outputResources:
            - name: gosvc_promoted_build_info

  - name: cd_demo_release_mgmt
    steps:
      - name: bundle
        type: CreateReleaseBundle
        configuration:
          releaseBundleName: demo_rb
          releaseBundleVersion: v1.0.${run_number}
          dryRun: false
          sign: false
          description: "some random test description"
          inputResources:
            - name: gosvc_promoted_build_info
              trigger: false
          outputResources:
            - name: release_bundle
          releaseNotes:
            syntax: markdown
            content: |
              ## Heading
                * Bullet
                * Points

      - name: sign
        type: SignReleaseBundle
        configuration:
          inputResources:
            - name: release_bundle
          outputResources:
            - name: signed_bundle

      - name: distribute
        type: DistributeReleaseBundle
        configuration:
          dryRun: false
          inputResources:
            - name: signed_bundle
            - name: distribution_rules
